---

- name: Convert {{ status_dir }}/openshift/cp4d-crio.conf to string
  shell:
    cat {{ status_dir }}/openshift/cp4d-crio.conf | \
      python3 -c "import sys, urllib.parse; print(urllib.parse.quote(''.join(sys.stdin.readlines())))"
  register: crio_conf_string

- name: Create CRI-O config MachineConfig file {{ status_dir }}/openshift/cp4d-crio-mc.yaml
  template:
    src: cp4d-crio-mc.j2
    dest: "{{ status_dir }}/openshift/cp4d-crio-mc.yaml"

- name: Apply CRI-O MachineConfig
  shell: oc apply -f {{ status_dir }}/openshift/cp4d-crio-mc.yaml
