---
- name: Create ConfigMap cp4d-crio-conf
  shell: |
    if ! oc get configmap -n kube-system cp4d-crio-conf;then
      oc create configmap -n kube-system cp4d-crio-conf \
        --from-file={{ status_dir }}/openshift/cp4d-crio.conf
    fi
- name: Set data for config map
  shell: |
    oc set data configmap/cp4d-crio-conf -n kube-system \
      --from-file={{ status_dir }}/openshift/cp4d-crio.conf
- name: Generate DaemonSet to set the CRI-O config for all nodes
  template:
    src: cp4d-crio-conf-ds.j2
    dest: "{{ status_dir }}/openshift/cp4d-crio-conf-ds.yaml"
- name: Create or replace DaemonSet cp4d-crio-conf-ds
  shell: |
    if oc get ds -n kube-system cp4d-crio-conf-ds;then
      oc delete ds -n kube-system cp4d-crio-conf-ds
    fi
    oc apply -f {{ status_dir }}/openshift/cp4d-crio-conf-ds.yaml
