- name: Install cartridges for CP4D cluster
  debug:
    msg: "Installing cartridges for CP4D cluster {{ current_cp4d_cluster.project }}"

- name: Prepare OpenShift operator subscriptions for each of the selected cp4d cartridges
  include_tasks: cp4d-create-subscriptions.yml
  loop: "{{ current_cp4d_cluster.cartridges | default([]) }}"
  loop_control:
    loop_var: current_cp4d_cartridge

- name: Get cartridges without dependent cartridges
  set_fact:
    cartridges_no_dep: "{{ current_cp4d_cluster.cartridges | json_query(cartr_no_dep_query) | default([]) }}"
  vars:
    cartr_no_dep_query: "[?dependencies == none]"

- name: Get cartridges with dependent cartridges
  set_fact:
    cartridges_with_dep: "{{ current_cp4d_cluster.cartridges | json_query(cartr_dep_query) | default([]) }}"
  vars:
    cartr_dep_query: "[?dependencies != none]"

#Install all cartridges without dependent cartridges
- name: Install custom resource (CR) for each of the selected cp4d cartridges (without dependencies)
  include_tasks: cp4d-install-cr.yml
  loop: "{{ cartridges_no_dep | default([]) }}"
  loop_control:
    loop_var: current_cp4d_cartridge

- name: Wait for cartridges to finish installation (without dependencies)
  include_tasks: cp4d-wait-cartridges-ready.yml
  vars: 
    wait_for_cartridges: "{{ cartridges_no_dep | default([]) }}"

#Install all cartridges with dependent cartridges
- name: Install custom resource (CR) for each of the selected cp4d cartridges (with dependencies)
  include_tasks: cp4d-install-cr.yml
  loop: "{{ cartridges_with_dep | default([]) }}"
  loop_control:
    loop_var: current_cp4d_cartridge

- name: Wait for cartridges to finish installation (with dependencies)
  include_tasks: cp4d-wait-cartridges-ready.yml
  vars: 
    wait_for_cartridges: "{{ cartridges_with_dep | default([]) }}"
