---
cp4d_saml_config:
- project: zen-40
  entrypoint: "https://prepiam.ice.ibmcloud.com/saml/sps/saml20ip/saml20"
  field_to_authenticate: email
  sp_cert_secret: ""
  idp_cert_secret: {{ env_id }}-zen-40-idp-cert
  issuer: "cp4d"
  identifier_format: ""
