---
cos:
- name: {{ env_id }}-cos
  plan: standard
  location: global

openshift:
- name: {{ env_id }}
  ocp_version: 4.8
  compute_flavour: bx2.16x64
  compute_nodes: 3
  infrastructure:
    type: vpc
    vpc_name: {{ env_id }}
    subnets: 
    - {{ env_id }}-subnet-zone-1
    - {{ env_id }}-subnet-zone-2
    - {{ env_id }}-subnet-zone-3
    cos_name: {{ env_id }}-cos
  openshift_storage:
  - storage_name: nfs-storage
    storage_type: nfs
    nfs_server_name: {{ env_id }}-nfs
  # - storage_name: ocs-storage
  #   storage_type: ocs
  #   ocs_storage_label: ocs
  #   ocs_storage_size_gb: 500
