---
# Create all catalog sources
- name: Prepare yaml file for catalog sources
  template:
    src: cpd-catalog-sources.j2
    dest: "{{ status_dir }}/cp4d/cpd-catalog-sources.yml"

- name: Install CatalogSources from {{ status_dir }}/cp4d/cpd-catalog-sources.yml
  shell: |
    oc apply -f {{ status_dir }}/cp4d/cpd-catalog-sources.yml
