---
- name: Show current CP4D cluster
  debug:
    msg: "Handling CP4D cluster {{ current_cp4d_cluster.project }}"

- include_role:
    name: cp4d-variables

- set_fact:
    _current_openshift_cluster: "{{ all_config.openshift | json_query(query) | first | default({}) }}"
  vars:
    query: >-
      [?name=='{{ current_cp4d_cluster.openshift_cluster_name }}']

- name: Login to the OpenShift cluster "{{ current_cp4d_cluster.openshift_cluster_name }}"
  include_role:
    name: openshift-login
  vars:
    _p_openshift_cluster_name: "{{ current_cp4d_cluster.openshift_cluster_name }}"

- name: Create Cloud Pak for Data directory for generated files
  file:
    path: "{{ status_dir }}/cp4d"
    state: directory

- name: Ensure the status log folder exists
  file:
    path: "{{status_dir}}/log"
    state: directory

- name: Prepare OpenShift cluster for Cloud Pak for Data
  include_role:
    name: cp4d-prepare-openshift
  when: ( current_cp4d_cluster.change_node_settings | default(True) | bool )

- set_fact:
    _use_case_files: False

- set_fact:
    _use_case_files: True
  when: (current_cp4d_cluster.image_registry_name | default("")) != "" or (current_cp4d_cluster.use_case_files | default(False) | bool)

- name: Remove case directory in case it exists and not air-gapped
  file:
    path: "{{ status_dir }}/cp4d/case"
    state: absent
  when: not (cpd_airgap | bool)

- name: Save case files for Cloud Pak for Data when using private registry or when explicitly using case files
  include_role: 
    name: cp4d-case-save
  vars:
    _p_current_cp4d_cluster: "{{ current_cp4d_cluster }}"
  when: 
  - _use_case_files
  - not (cpd_airgap | bool)

# Mirror from the entitled registry if not airgapped and entitlement key found in vault
- block:
  - name: Get IBM Entitled Registry key
    include_role: 
      name: vault-get-secret
    vars:
      secret_name: "ibm_cp_entitlement_key"
      secret_group: "{{ environment_name }}"
  - set_fact:
      ibm_cp_entitlement_key: "{{ secret_value }}"

  - name: Mirror images for Cloud Pak for Data from entitled to private registry {{ current_cp4d_cluster.image_registry_name }}
    include_role: 
      name: cp-mirror-images
    vars:
      _p_target_registry_hostname: "{{ current_image_registry.registry_host_name }}"
      _p_target_registry_port: "{{ current_image_registry.registry_port | default('') }}"
      _p_target_registry_namespace: "{{ current_image_registry.registry_namespace | default('') }}"
      _p_target_registry_credentials_secret: "image-registry-{{ current_cp4d_cluster.image_registry_name }}"
      _p_case_dir: "{{ status_dir }}/cp4d/case"
    when: 
    - ibm_cp_entitlement_key | default("") != ""
  when: 
  - (current_cp4d_cluster.image_registry_name | default("")) != ""
  - not (cpd_airgap | bool)
  - not (cpd_skip_mirror | bool)

# Mirror from portable registry if airgapped
- name: Mirror images for Cloud Pak for Data from portable to private registry {{ current_cp4d_cluster.image_registry_name }}
  include_role: 
    name: cp-mirror-images
  vars:
    _p_source_registry_hostname: "{{ lookup('file', status_dir + '/imageregistry/portable-registry-ip.out') }}"
    _p_source_registry_port: "5000"
    _p_source_registry_credentials_secret: "portable-registry-credentials"
    _p_target_registry_hostname: "{{ current_image_registry.registry_host_name }}"
    _p_target_registry_port: "{{ current_image_registry.registry_port | default('') }}"
    _p_target_registry_namespace: "{{ current_image_registry.registry_namespace | default('') }}"
    _p_target_registry_credentials_secret: "image-registry-{{ current_cp4d_cluster.image_registry_name }}"
    _p_case_dir: "{{ status_dir }}/cp4d/case"
  when: 
  - (current_cp4d_cluster.image_registry_name | default("")) != ""
  - cpd_airgap | bool
  - not (cpd_skip_mirror | bool)
  
- name: Create catalog sources for entitled registry when not using case files
  include_tasks: create-catalog-sources-entitled.yml
  when: not _use_case_files

- name: Create catalog sources from case files in {{ status_dir }}/cp4d/case directory when using case files
  include_tasks: create-catalog-source-case-file.yml
  loop: "{{ case_inventories }}"
  loop_control:
    loop_var: case_inventory
  when: _use_case_files

- name: Get OpenShift storage classes to use for {{ current_cp4d_cluster.project }} and storage class name {{ current_cp4d_cluster.storage_class_name }}
  include_tasks: cp4d-get-storage-classes.yml

- name: Prepare Cloud Pak for Data operator
  include_tasks: prepare-cp4d-operator-40.yml

- name: Prepare OpenShift project {{ current_cp4d_cluster.project }} for Cloud Pak for Data
  include_tasks: openshift-prepare-project.yml

- name: Install Control Plane for Cloud Pak for Data
  include_tasks: install-control-plane-40.yml

- name: Add Cloud Pak for Data route to /etc/hosts for vSphere
  include_tasks: vsphere-configure-etc-hosts.yml
  when: cloud_platform == "vsphere"

- name: Configure CP4D admin password and store in vault
  include_tasks: configure-cpd-admin-password.yml

- name: Output Cloud pak for Data URL and admin password
  include_role:
    name: cp4d-cluster-show

- name: Retrieve Cloud Pak Foundational Services 
  set_fact:
    _cp_fs: "{{ current_cp4d_cluster.cartridges | json_query(query) | first | default({}) }}"
  vars:
    query: >-
      [?name=='cp-foundation']

- name: Show foundational services element
  debug:
    var: _cp_fs

- name: Activate or deactivate license service
  include_role:
    name: cp-fs-license-service
  vars:
    _p_fs_project: "{{ foundational_services_project }}"
    _p_license_service: "{{ _cp_fs.license_service | default({}) }}"

- name: Delete obsolete cartridges
  include_role:
    name: cp4d-cartridge-remove

- name: Install selected cartridges for the cluster
  include_role:
    name: cp4d-cartridge-install
