---
- debug:
    msg: "{{ lookup('template','openshift-clusterlogforwarder-patch-output.j2') }}"

- name: Patch ClusterLogForwarder output
  shell: |
    oc patch -n openshift-logging clusterlogforwarder/instance --type=merge \
      --patch {{ lookup('template','openshift-clusterlogforwarder-patch-output.j2') }}