---
cos:
- name: {{ env_id }}-cos
  plan: standard
  location: global

openshift:
- name: {{ env_id }}
  ocp_version: 4.8
  compute_flavour: bx2.16x64
  compute_nodes: 3
  infrastructure:
    type: vpc
    vpc_name: {{ env_id }}
    subnets: 
    - {{ env_id }}-subnet-zone-1
    - {{ env_id }}-subnet-zone-2
    - {{ env_id }}-subnet-zone-3
    cos_name: {{ env_id }}-cos
  openshift_storage:
  - storage_name: pwx-storage
    storage_type: pwx 
    pwx_etcd_location: {{ ibm_cloud_region }}
    pwx_storage_size_gb: 200
    pwx_storage_iops: 10
    pwx_storage_profile: "10iops-tier"
    portworx_version: 2.7.2
    stork_version: 2.6.2
