---

- name: Validate mandatory variables are defined
  assert:
    that:
      - cloud_platform is defined
      - current_openshift_storage is defined

- name: Validate cloud_platform is implemented
  fail: msg="cloud_platform {{ cloud_platform }} is not implemented, current implemented cloud platforms are {{ implemented_cloud_platform_types }} "
  when: "cloud_platform not in implemented_cloud_platform_types"

- name: Processing storage class
  debug:
    var: current_openshift_storage

- name: Configure NFS storage class
  include_role: 
    name: nfs-storage-class
  when: current_openshift_storage.storage_type == 'nfs'

- name: Configure OCS storage class
  include_role: 
    name: ocs-storage-class
  when: current_openshift_storage.storage_type == 'ocs'
  
- name: Configure Portworx storage class
  include_role: 
    name: pwx-storage-class
  when: current_openshift_storage.storage_type == 'pwx'

- name: Configure ibmc-file-gold-gid storage class
  include_role: 
    name: ibmc-file-gold-gid-storage-class
  when: 
    - current_openshift_storage.storage_type == 'custom'
    - current_openshift_storage.ocp_storage_class_file == 'ibmc-file-gold-gid'