---
- block:
  - set_fact:
      _configured_cartridge: "{{ current_cp4d_cluster.cartridges | json_query(query) | first | default({}) }}"
    vars:
      query: >-
        [?name=='{{ _current_cartridge_cr.name }}']

  - name: Check if cartridge {{ _current_cartridge_cr.name }} is currently installed
    shell: |
      oc get {{ _current_cartridge_cr.cr_cr }} --namespace {{ current_cp4d_cluster.project }}
    failed_when: False
    register: _cartridge_installed

  - name: Remove cartridge if it is installed but has been removed in the mean time
    shell: |
      oc delete {{ _current_cartridge_cr.cr_cr }} --namespace {{ current_cp4d_cluster.project }} --all
    when: >
      _cartridge_installed.rc == 0 and 
        ( _configured_cartridge == {} or ( (_configured_cartridge.state | default('installed')) == 'removed' ) )
  when: not (_current_cartridge_cr.embedded | default(False) | bool)