---
azure_aro:
- name: {{ env_id }}-infra
  resource_group:
    name: {{ env_id }}-rg
    location: {{ azure_location }}
  vnet:
    name: {{ env_id }}-vnet
    address_space: 10.0.0.0/22
  control_plane:
    subnet:
      name: {{ env_id }}-control-plane-subnet
      address_prefixes: 10.0.0.0/23
    vm:
      size: Standard_D8s_v3
  compute:
    subnet:
      name: {{ env_id }}-compute-subnet
      address_prefixes: 10.0.2.0/23
    vm:
      size: Standard_D16s_v3
      disk_size_gb: 128
      count: 3