---
- name: Handle TLS certificate configuration for CP4D cluster
  debug:
    msg: "Handling TLS certificate configuration for CP4D cluster {{ current_cp4d_cluster.openshift_cluster_name }}"

- name: Configure TLS Certificate Cloud Pak for Data on IBM Cloud
  include_tasks: configure-ssl-certificate-ibm-cloud.yml
  when: cloud_platform == 'ibm-cloud'

