---
- name: Validate if Dynamic NFS Storage {{ nfs_storage_class_name }}  class exists
  shell: |
    oc get sc {{ nfs_storage_class_name }}
  failed_when: False
  register: oc_storage_class_exists

- name: Install NFS Storage class {{ nfs_storage_class_name }}
  block:
    - set_fact:
        _nfs_server: "{{ all_config.nfs_server | json_query(query) | first | default({}) }}"
      vars:
        query: >-
          [?name=='{{ current_openshift_storage.nfs_server_name }}']

    - name: Retrieve Terraform tfstate from the vault for IBM Cloud
      include_role: 
        name: vault-get-secret
      vars:
        secret_name: "{{ environment_name }}-terraform-tfstate"
        secret_group: "{{ environment_name }}"
      when: cloud_platform == 'ibm-cloud'

    - set_fact:
        tfstate: "{{ secret_value }}"   
      when: cloud_platform == 'ibm-cloud'       

    # Retrieve the private IP address of the NFS server
    - set_fact:
        _nfs_server_ip: "{{ tfstate.resources | json_query(query) | first }}"
      vars:
        query: >-
          [?type=='ibm_is_instance' && instances[0].attributes.name=='{{ _nfs_server.name }}'].instances[0].attributes.primary_network_interface[0].primary_ipv4_address
      when: cloud_platform == 'ibm-cloud' 

    - name: NFS Server IP address
      debug:
        msg: "{{ _nfs_server_ip }}"
      when: cloud_platform == 'ibm-cloud' 

    - set_fact:
        nfs_storage_server_ip: "{{ _nfs_server_ip }}"
        nfs_storage_server_path: "{{ _nfs_server.infrastructure.storage_folder }}"
      when: cloud_platform == 'ibm-cloud'

    - set_fact:
        nfs_storage_server_ip: "{{ _nfs_server.infrastructure.host_ip }}"
        nfs_storage_server_path: "{{ _nfs_server.infrastructure.storage_folder }}"
      when: cloud_platform == 'vsphere'

    - tempfile:
        state: directory
      register: nfs_temp_dir

    - name: Show NFS temporary directory
      debug:
        msg: "{{ nfs_temp_dir }}"

    - name: Create OpenShift Project {{ nfs_storage_class_project }}
      shell: |
        oc get project {{ nfs_storage_class_project }} > /dev/null 2>&1 || \
          oc new-project {{ nfs_storage_class_project }}

    - name: Create Dynamic NFS rbac.yaml
      template:
        src: rbac.yaml.j2
        dest: "{{ nfs_temp_dir.path }}/rbac.yaml"

    - name: Create Dynamic NFS deployment.yaml
      template:
        src: deployment.yaml.j2
        dest: "{{ nfs_temp_dir.path }}/deployment.yaml"

    - name: Create Dynamic NFS class.yaml
      template:
        src: class.yaml.j2
        dest: "{{ nfs_temp_dir.path }}/class.yaml"

    - name: Process Dynamic NFS rbac.yaml
      shell: "oc create -f {{ nfs_temp_dir.path }}/rbac.yaml"

    - name: Set scc to nfs-client-provisioner
      shell: "oc adm policy add-scc-to-user hostmount-anyuid system:serviceaccount:{{ nfs_storage_class_project }}:nfs-client-provisioner"

    - name: Create the Storage class
      shell: "oc create -f {{ nfs_temp_dir.path }}/class.yaml"

    - name: Create the nfs-client-provisioner
      shell: "oc create -f {{ nfs_temp_dir.path }}/deployment.yaml"

    - name: Wait 15 seconds for the dynamic NFS client to deploy
      pause:
        seconds: 15

  when: oc_storage_class_exists.rc != 0
