---
openshift:
- name: {{ env_id }}
  ocp_version: 4.8
  cluster_name: {{ env_id }}
  domain_name: example.com
  openshift_storage:
  - storage_name: nfs-storage
    storage_type: nfs
# Optional parameters if you want to override the storage class used
    # ocp_storage_class_file: nfs-client 
    # ocp_storage_class_block: nfs-client
