---
nfs_server:
- name: sample-nfs
  infrastructure:
    host_ip: 10.99.92.31
    storage_folder: /data/nfs    

vsphere:
- name: {{ env_id }}
  vcenter: 10.99.92.13
  datacenter: Datacenter1
  datastore: Datastore1
  cluster: Cluster1
  network: "VM Network"
  folder: /Datacenter1/vm/{{ env_id }}

vm_definition:
- name: control-plane
  vcpu: 8
  memory_mb: 32768
  boot_disk_size_gb: 100
- name: compute
  vcpu: 16
  memory_mb: 65536
  boot_disk_size_gb: 200
- name: storage
  vcpu: 10
  memory_mb: 32768
  boot_disk_size_gb: 100
  # Optional overrides for vsphere properties
  # datastore: Datastore1
  # network: "VM Network"
