---
- name: Get first compute node
  shell: |
    oc get no --no-headers -l node-role.kubernetes.io/worker -o custom-columns='name:.metadata.name' | head -1
  register: _ocp_compute_nodes

- name: Retrieve /etc/kubernetes/kubelet.conf
  shell: |
    {{ lookup('template','oc-debug-kubelet.j2') }}
  register: debug_node_result
  retries: 3
  delay: 10
  until: debug_node_result.rc==0

- name: Append allowedUnsafeSysctls to kubelet.conf
  blockinfile:
    path: "{{ status_dir }}/openshift/cp4d-kubelet.conf"
    block: |
      allowedUnsafeSysctls:
        - "kernel.msg*"
        - "kernel.shm*"
        - "kernel.sem"

- name: Create ConfigMap cp4d-kubelet-conf
  shell: |
    if ! oc get configmap -n kube-system cp4d-kubelet-conf;then
      oc create configmap -n kube-system cp4d-kubelet-conf \
        --from-file={{ status_dir }}/openshift/cp4d-kubelet.conf
    fi
- name: Set data for config map
  shell: |
    oc set data configmap/cp4d-kubelet-conf -n kube-system \
      --from-file={{ status_dir }}/openshift/cp4d-kubelet.conf
- name: Generate DaemonSet to set Kubelet configuration for all nodes
  template:
    src: cp4d-kubelet-conf-ds.j2
    dest: "{{ status_dir }}/openshift/cp4d-kubelet-conf-ds.yaml"
- name: Create or replace DaemonSet cp4d-kubelet-conf-ds
  shell: |
    if oc get ds -n kube-system cp4d-kubelet-conf-ds;then
      oc delete ds -n kube-system cp4d-kubelet-conf-ds
    fi
    oc apply -f {{ status_dir }}/openshift/cp4d-kubelet-conf-ds.yaml
