---
- include_role:
    name: cp4d-variables
    
- set_fact:
    _case_dir: "{{ status_dir }}/cp4d/case"

- name: Create directory {{ _case_dir }} for case files
  file:
    path: "{{ _case_dir }}"
    state: directory

- name: Show current Cloud Pak for Data cluster
  debug:
    var: _p_current_cp4d_cluster

- name: Download operator case files to {{ status_dir }}/cp4d/case
  include_tasks: download-case-online.yml
  loop: "{{ _p_current_cp4d_cluster.cartridges | default([]) }}"
  loop_control:
    loop_var: _current_cp4d_cartridge