---
- name: 50 - Install Cloud Pak
  hosts: localhost
  connection: local
  become: True
  gather_facts: False
  environment:
    KUBECONFIG: "{{ status_dir }}/openshift/kubeconfig"

  vars:
    ansible_callback_diy_runner_on_skipped_msg: ""
    ansible_callback_diy_runner_on_ok_msg: ""
    ansible_callback_diy_playbook_on_include_msg: ""

  tasks:
  - name: Remove obsolete Cloud Pak for Data installations
    include_role:
      name: cp4d-cluster-delete

  - name: Install Cloud Pak for Data
    include_role:
      name: cp4d-cluster
    loop: "{{ all_config.cp4d | default([]) }}"
    loop_control:
      loop_var: current_cp4d_cluster
