---
- name: Validate mandatory variables are defined
  assert:
    that:
      - cloud_platform is defined

- name: Validate cloud_platform is implemented
  fail: msg="cloud_platform {{ cloud_platform }} is not implemented, current implemented cloud platforms are {{ implemented_cloud_platform_types }} "
  when: "cloud_platform not in implemented_cloud_platform_types"

- name: Retrieve rosa-login-token secret from the vault
  include_role: 
    name: vault-get-secret
  vars:
    secret_name: "rosa-login-token"
    secret_group: "{{ environment_name }}"

- set_fact:
    _rosa_login_token: "{{ secret_value }}"

- name: Login to ROSA
  shell: |
    rosa login --token="{{ _rosa_login_token }}"