---
cos:
- name: {{ env_id }}-cos
  plan: standard
  location: global

openshift:
- name: {{ env_id }}
  ocp_version: 4.8
  compute_flavour: bx2.16x64
  compute_nodes: 5
  infrastructure:
    type: vpc
    vpc_name: {{ env_id }}
    subnets: 
    - {{ env_id }}-subnet
    cos_name: {{ env_id }}-cos
  openshift_storage:
  - storage_name: nfs-storage
    storage_type: nfs
    nfs_server_name: {{ env_id }}-nfs