---
- name: Validate mandatory variables are defined
  assert:
    that:
      - cloud_platform is defined

- include_tasks: ibmcloud-download-cli.yml
  when: cloud_platform == 'ibm-cloud'

- include_tasks: aws-download-cli.yml
  when: cloud_platform == 'aws'

- include_tasks: azure-download-cli.yml
  when: cloud_platform == 'azure'

- name: Download and install cloudctl
  include_role:
    name: cloudctl-download

- name: Download OpenShift client
  include_role:
    name: openshift-download-client
  vars:
    _p_ocp_version: "{{ _current_openshift_cluster.ocp_version }}"
  loop: "{{ all_config.openshift | default([]) }}"
  loop_control:
    loop_var: _current_openshift_cluster
