---
- name: Write secret to file {{ secret_file }} if one was specified
  shell: |
    echo "{{ _secret_value_b64 }}" | base64 -d > "{{ secret_file }}"
  when: secret_value != ''

- name: Write empty value to file {{ secret_file }} if secret was not found
  shell: |
    echo "" > "{{ secret_file }}"
  when: secret_value == ''

